name = "entitybuilders-site"
compatibility_date = "2025-05-01"
routes = [
  { pattern = "entitybuilders.ai/*", zone_name = "entitybuilders.ai" },
  { pattern = "www.entitybuilders.ai/*", zone_name = "entitybuilders.ai" }
]

[assets]
directory = "./dist"
